-- AUTO-GENERATED by scripts/gen-bootstrap.mjs — full PerkPilot backend.

-- ============================================================
-- migrations/0001_schema.sql
-- ============================================================
-- PerkPilot schema (build plan §3). The card_catalog and program_reference
-- tables are the product; everything else is per-household instance data.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
create type household_role     as enum ('owner', 'member');
create type card_network       as enum ('visa', 'mastercard', 'amex', 'discover');
create type catalog_status     as enum ('active', 'discontinued', 'application_paused');
create type benefit_type       as enum ('free_night_cert', 'statement_credit', 'lounge', 'companion_pass', 'other');
create type reset_cycle        as enum ('annual', 'calendar_year', 'cardmember_year', 'one_time');
create type user_card_status   as enum ('open', 'closed', 'product_changed');
create type expiration_policy  as enum ('inactivity_months', 'hard_date', 'none');
create type points_account_type as enum ('loyalty', 'vacation_club');
create type pricing_model      as enum ('fixed_chart', 'dynamic', 'revenue_based');

-- ---------------------------------------------------------------------------
-- Households + users
-- ---------------------------------------------------------------------------
create table households (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  created_at  timestamptz not null default now()
);

-- users.id == auth.uid()
create table users (
  id            uuid primary key references auth.users (id) on delete cascade,
  household_id  uuid not null references households (id) on delete cascade,
  display_name  text not null,
  email         text not null,
  role          household_role not null default 'member'
);
create index users_household_idx on users (household_id);

-- ---------------------------------------------------------------------------
-- Global catalog (admin-maintained) — the benefits database
-- ---------------------------------------------------------------------------
create table card_catalog (
  id                uuid primary key default gen_random_uuid(),
  issuer            text not null,
  product_name      text not null,
  network           card_network not null,
  annual_fee        numeric not null default 0,
  referral_url      text,
  referral_active   boolean not null default false,
  earn_rates        jsonb not null default '{}'::jsonb,   -- category -> multiplier
  benefits_template jsonb not null default '[]'::jsonb,   -- BenefitTemplate[]
  last_verified_at  date not null default current_date,   -- critical: surfaced in UI
  status            catalog_status not null default 'active'
);

-- ---------------------------------------------------------------------------
-- User-owned instances
-- ---------------------------------------------------------------------------
create table user_cards (
  id                   uuid primary key default gen_random_uuid(),
  user_id              uuid not null references users (id) on delete cascade,
  catalog_id           uuid not null references card_catalog (id),
  opened_date          date,
  annual_fee_due_date  date,
  last4                text,
  nickname             text,
  status               user_card_status not null default 'open'
);
create index user_cards_user_idx on user_cards (user_id);

create table benefits (
  id                 uuid primary key default gen_random_uuid(),
  user_card_id       uuid not null references user_cards (id) on delete cascade,
  type               benefit_type not null,
  name               text not null,
  est_value_usd      numeric not null default 0,
  expiration_date    date,
  reset_cycle        reset_cycle not null,
  used               boolean not null default false,
  used_date          date,
  notify_days_before integer[] not null default '{30,7,1}'
);
create index benefits_card_idx on benefits (user_card_id);

create table points_accounts (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references users (id) on delete cascade,
  program             text not null,
  balance             numeric not null default 0,
  balance_updated_at  timestamptz not null default now(),
  expiration_policy   expiration_policy not null default 'none',
  inactivity_deadline date,
  hard_deadline       date,
  account_type        points_account_type not null default 'loyalty'
);
create index points_accounts_user_idx on points_accounts (user_id);

-- ---------------------------------------------------------------------------
-- Global program reference — powers the estimator
-- ---------------------------------------------------------------------------
create table program_reference (
  program              text primary key,
  display_name         text not null,
  cpp_low              numeric not null,
  cpp_mid              numeric not null,
  cpp_high             numeric not null,
  pricing_model        pricing_model not null,
  chart                jsonb,
  transfer_partners    jsonb,
  expiration_rule_text text not null default ''
);

-- ============================================================
-- migrations/0002_rls.sql
-- ============================================================
-- Row Level Security: household sharing is "just an RLS policy" (build plan §5).
-- Every instance table is scoped to the caller's household; the two global
-- catalog tables are world-readable but admin-only for writes.

-- Helper: the household_id of the currently authenticated user.
create or replace function current_household_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select household_id from users where id = auth.uid();
$$;

alter table households        enable row level security;
alter table users             enable row level security;
alter table user_cards        enable row level security;
alter table benefits          enable row level security;
alter table points_accounts   enable row level security;
alter table card_catalog      enable row level security;
alter table program_reference enable row level security;

-- households: members can see/update their own household.
create policy households_select on households
  for select using (id = current_household_id());
create policy households_update on households
  for update using (id = current_household_id());

-- users: visible to everyone in the same household.
create policy users_select on users
  for select using (household_id = current_household_id());
create policy users_insert_self on users
  for insert with check (id = auth.uid());
create policy users_update_self on users
  for update using (id = auth.uid());

-- user_cards: scoped via the owning user's household.
create policy user_cards_all on user_cards
  for all using (
    user_id in (select id from users where household_id = current_household_id())
  )
  with check (
    user_id in (select id from users where household_id = current_household_id())
  );

-- benefits: scoped via the parent user_card's household.
create policy benefits_all on benefits
  for all using (
    user_card_id in (
      select uc.id from user_cards uc
      join users u on u.id = uc.user_id
      where u.household_id = current_household_id()
    )
  )
  with check (
    user_card_id in (
      select uc.id from user_cards uc
      join users u on u.id = uc.user_id
      where u.household_id = current_household_id()
    )
  );

-- points_accounts: scoped via the owning user's household.
create policy points_accounts_all on points_accounts
  for all using (
    user_id in (select id from users where household_id = current_household_id())
  )
  with check (
    user_id in (select id from users where household_id = current_household_id())
  );

-- Global tables: readable by any authenticated user, writable by admin only
-- (service role bypasses RLS, so no write policy is exposed to clients).
create policy card_catalog_read on card_catalog
  for select using (auth.role() = 'authenticated');
create policy program_reference_read on program_reference
  for select using (auth.role() = 'authenticated');

-- ============================================================
-- migrations/0003_value_at_risk.sql
-- ============================================================
-- The flagship derived view (build plan §3): "a query, not a table". Every
-- unused benefit expiring within 90 days + every points account within 120
-- days of an expiration deadline. RLS on the underlying tables means this view
-- is automatically scoped per household.

create or replace view value_at_risk as
  select
    'benefit'::text                         as kind,
    b.id                                    as id,
    uc.user_id                              as user_id,
    b.name                                  as title,
    (cc.issuer || ' ' || cc.product_name)   as subtitle,
    b.est_value_usd                         as est_value_usd,
    b.expiration_date                       as deadline,
    (b.expiration_date - current_date)      as days_left,
    case
      when b.expiration_date - current_date <= 7  then 'red'
      when b.expiration_date - current_date <= 30 then 'amber'
      else 'green'
    end                                     as urgency
  from benefits b
  join user_cards uc   on uc.id = b.user_card_id
  join card_catalog cc on cc.id = uc.catalog_id
  where b.used = false
    and b.expiration_date is not null
    and b.expiration_date >= current_date
    and b.expiration_date <= current_date + 90

  union all

  select
    'points'::text                          as kind,
    p.id                                    as id,
    p.user_id                               as user_id,
    (to_char(p.balance, 'FM999,999,999') || ' ' || coalesce(pr.display_name, p.program) || ' points') as title,
    case when p.account_type = 'vacation_club'
         then 'Vacation club — hard lapse'
         else 'Expiring from inactivity' end as subtitle,
    0::numeric                              as est_value_usd,
    coalesce(p.hard_deadline, p.inactivity_deadline) as deadline,
    (coalesce(p.hard_deadline, p.inactivity_deadline) - current_date) as days_left,
    case
      when coalesce(p.hard_deadline, p.inactivity_deadline) - current_date <= 30  then 'red'
      when coalesce(p.hard_deadline, p.inactivity_deadline) - current_date <= 120 then 'amber'
      else 'green'
    end                                     as urgency
  from points_accounts p
  left join program_reference pr on pr.program = p.program
  where coalesce(p.hard_deadline, p.inactivity_deadline) is not null
    and coalesce(p.hard_deadline, p.inactivity_deadline) >= current_date
    and coalesce(p.hard_deadline, p.inactivity_deadline) <= current_date + 120

  order by days_left;

-- ============================================================
-- migrations/0004_add_card_trigger.sql
-- ============================================================
-- "Add card from catalog" auto-populates that card's benefits with default
-- expirations (build plan Phase 1). Done server-side via a trigger so both the
-- app and the future web frontend get identical behaviour.

create or replace function materialize_card_benefits()
returns trigger
language plpgsql
as $$
declare
  tmpl jsonb;
  cycle text;
  exp_date date;
begin
  for tmpl in
    select jsonb_array_elements(benefits_template)
    from card_catalog where id = new.catalog_id
  loop
    cycle := tmpl->>'reset_cycle';
    exp_date := case cycle
      when 'calendar_year'   then make_date(extract(year from current_date)::int, 12, 31)
      when 'cardmember_year' then coalesce(new.opened_date, current_date) + interval '1 year'
      when 'annual'          then current_date + interval '1 year'
      else null
    end;

    insert into benefits (user_card_id, type, name, est_value_usd, expiration_date, reset_cycle, notify_days_before)
    values (
      new.id,
      (tmpl->>'type')::benefit_type,
      tmpl->>'name',
      coalesce((tmpl->>'est_value_usd')::numeric, 0),
      exp_date,
      cycle::reset_cycle,
      coalesce(
        (select array_agg((v)::int) from jsonb_array_elements_text(tmpl->'notify_days_before') v),
        '{30,7,1}'::int[]
      )
    );
  end loop;
  return new;
end;
$$;

create trigger trg_materialize_card_benefits
  after insert on user_cards
  for each row execute function materialize_card_benefits();

-- ============================================================
-- migrations/0005_retention_offers.sql
-- ============================================================
-- Retention-offer crowdsourcing (build plan §10, idea #2). Unlike the other
-- instance tables, reports are READABLE by every authenticated user so the app
-- can aggregate them — but each user can only insert/modify their own rows.
-- No PII is exposed by the read policy (no names/emails on this table).

create type retention_outcome   as enum ('kept', 'downgraded', 'canceled');
create type retention_channel   as enum ('phone', 'chat', 'app');
create type retention_offer_type as enum ('points', 'statement_credit', 'fee_waiver', 'spend_bonus', 'none');

create table retention_offers (
  id              uuid primary key default gen_random_uuid(),
  catalog_id      uuid not null references card_catalog (id),
  user_id         uuid not null references users (id) on delete cascade,
  reported_at     date not null default current_date,
  channel         retention_channel not null,
  offer_type      retention_offer_type not null,
  points_offered  integer,
  value_usd       numeric,
  spend_required  numeric,
  note            text,
  outcome         retention_outcome not null
);
create index retention_offers_catalog_idx on retention_offers (catalog_id);

alter table retention_offers enable row level security;

-- Aggregate reads: any authenticated user can read all reports.
create policy retention_read on retention_offers
  for select using (auth.role() = 'authenticated');

-- Writes: only for your own user_id.
create policy retention_insert on retention_offers
  for insert with check (user_id = auth.uid());
create policy retention_update on retention_offers
  for update using (user_id = auth.uid());
create policy retention_delete on retention_offers
  for delete using (user_id = auth.uid());

-- ============================================================
-- migrations/0006_onboarding.sql
-- ============================================================
-- Onboarding: a brand-new authenticated user has no household yet, so RLS would
-- show them an empty app. These security-definer RPCs bootstrap the first
-- household (owner) or join an existing one by invite code — the only writes a
-- user without a household row is allowed to make.

alter table households
  add column invite_code text unique default upper(substr(md5(random()::text), 1, 6));

-- Create a household and make the caller its owner.
create or replace function create_household(p_name text, p_display_name text)
returns households
language plpgsql
security definer
set search_path = public
as $$
declare
  h households;
begin
  if exists (select 1 from users where id = auth.uid()) then
    raise exception 'You already belong to a household';
  end if;
  insert into households (name)
    values (coalesce(nullif(trim(p_name), ''), 'My Household'))
    returning * into h;
  insert into users (id, household_id, display_name, email, role)
    values (auth.uid(), h.id, coalesce(nullif(trim(p_display_name), ''), 'Me'),
            coalesce(auth.jwt() ->> 'email', ''), 'owner');
  return h;
end;
$$;

-- Join an existing household by its invite code.
create or replace function join_household(p_code text, p_display_name text)
returns households
language plpgsql
security definer
set search_path = public
as $$
declare
  h households;
begin
  select * into h from households where invite_code = upper(trim(p_code));
  if h.id is null then
    raise exception 'Invalid invite code';
  end if;
  insert into users (id, household_id, display_name, email, role)
    values (auth.uid(), h.id, coalesce(nullif(trim(p_display_name), ''), 'Me'),
            coalesce(auth.jwt() ->> 'email', ''), 'member')
    on conflict (id) do nothing;
  return h;
end;
$$;

grant execute on function create_household(text, text) to authenticated;
grant execute on function join_household(text, text) to authenticated;

-- ============================================================
-- seed.sql (global catalog + program_reference)
-- ============================================================
-- AUTO-GENERATED by scripts/gen-seed.ts — do not edit by hand.
-- Seed for the two global tables that "are the product".

-- Card catalog
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_amex_platinum', 'American Express', 'The Platinum Card', 'amex', 695, null, false, '{"flights":5,"hotels":5,"other":1}'::jsonb, '[{"type":"statement_credit","name":"Airline Fee Credit","est_value_usd":200,"reset_cycle":"calendar_year","notify_days_before":[60,14,3]},{"type":"statement_credit","name":"Hotel Credit","est_value_usd":200,"reset_cycle":"calendar_year","notify_days_before":[60,14,3]},{"type":"statement_credit","name":"Uber Cash (monthly)","est_value_usd":200,"reset_cycle":"calendar_year","notify_days_before":[7,1]},{"type":"statement_credit","name":"Saks Credit","est_value_usd":100,"reset_cycle":"calendar_year","notify_days_before":[30,7]},{"type":"lounge","name":"Centurion / Priority Pass Lounge Access","est_value_usd":0,"reset_cycle":"annual","notify_days_before":[]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_amex_gold', 'American Express', 'American Express Gold Card', 'amex', 325, null, false, '{"dining":4,"groceries":4,"flights":3,"other":1}'::jsonb, '[{"type":"statement_credit","name":"Dining Credit (monthly)","est_value_usd":120,"reset_cycle":"calendar_year","notify_days_before":[7,1]},{"type":"statement_credit","name":"Uber Cash (monthly)","est_value_usd":120,"reset_cycle":"calendar_year","notify_days_before":[7,1]},{"type":"statement_credit","name":"Resy Credit","est_value_usd":100,"reset_cycle":"calendar_year","notify_days_before":[30,7]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_amex_green', 'American Express', 'American Express Green Card', 'amex', 150, null, false, '{"travel":3,"dining":3,"transit":3,"other":1}'::jsonb, '[{"type":"statement_credit","name":"CLEAR Plus Credit","est_value_usd":199,"reset_cycle":"calendar_year","notify_days_before":[60,14]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_csp', 'Chase', 'Sapphire Preferred', 'visa', 95, null, false, '{"travel":2,"dining":3,"streaming":3,"other":1}'::jsonb, '[{"type":"statement_credit","name":"Hotel Credit","est_value_usd":50,"reset_cycle":"cardmember_year","notify_days_before":[60,14]},{"type":"other","name":"Anniversary Points Bonus (10%)","est_value_usd":0,"reset_cycle":"cardmember_year","notify_days_before":[]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_csr', 'Chase', 'Sapphire Reserve', 'visa', 550, null, false, '{"travel":3,"dining":3,"other":1}'::jsonb, '[{"type":"statement_credit","name":"Travel Credit","est_value_usd":300,"reset_cycle":"cardmember_year","notify_days_before":[60,14,3]},{"type":"lounge","name":"Priority Pass Select","est_value_usd":0,"reset_cycle":"annual","notify_days_before":[]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_venture_x', 'Capital One', 'Venture X', 'visa', 395, null, false, '{"travel_portal":10,"hotels_portal":10,"other":2}'::jsonb, '[{"type":"statement_credit","name":"Travel Portal Credit","est_value_usd":300,"reset_cycle":"cardmember_year","notify_days_before":[60,14]},{"type":"other","name":"Anniversary Miles (10k)","est_value_usd":100,"reset_cycle":"cardmember_year","notify_days_before":[14]},{"type":"lounge","name":"Capital One / Priority Pass Lounges","est_value_usd":0,"reset_cycle":"annual","notify_days_before":[]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_venture', 'Capital One', 'Venture Rewards', 'visa', 95, null, false, '{"other":2,"hotels_portal":5}'::jsonb, '[{"type":"statement_credit","name":"Global Entry / TSA PreCheck Credit","est_value_usd":120,"reset_cycle":"one_time","notify_days_before":[]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_bonvoy_brilliant', 'American Express', 'Marriott Bonvoy Brilliant', 'amex', 650, null, false, '{"marriott":6,"dining":3,"flights":3,"other":2}'::jsonb, '[{"type":"free_night_cert","name":"Annual Free Night Award (85k)","est_value_usd":600,"reset_cycle":"cardmember_year","notify_days_before":[60,30,7]},{"type":"statement_credit","name":"Dining Credit (monthly)","est_value_usd":300,"reset_cycle":"calendar_year","notify_days_before":[7,1]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_bonvoy_boundless', 'Chase', 'Marriott Bonvoy Boundless', 'visa', 95, null, false, '{"marriott":6,"groceries":3,"gas":3,"other":2}'::jsonb, '[{"type":"free_night_cert","name":"Annual Free Night Award (35k)","est_value_usd":250,"reset_cycle":"cardmember_year","notify_days_before":[60,30,7]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_bonvoy_bevy', 'American Express', 'Marriott Bonvoy Bevy', 'amex', 250, null, false, '{"marriott":6,"dining":4,"groceries":4,"other":2}'::jsonb, '[{"type":"free_night_cert","name":"Annual Free Night Award (50k)","est_value_usd":350,"reset_cycle":"cardmember_year","notify_days_before":[60,30,7]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_hilton_aspire', 'American Express', 'Hilton Honors Aspire', 'amex', 550, null, false, '{"hilton":14,"flights":7,"dining":7,"other":3}'::jsonb, '[{"type":"free_night_cert","name":"Annual Free Night Reward","est_value_usd":800,"reset_cycle":"cardmember_year","notify_days_before":[60,30,7]},{"type":"statement_credit","name":"Airline Credit (semi-annual)","est_value_usd":200,"reset_cycle":"calendar_year","notify_days_before":[45,14]},{"type":"statement_credit","name":"Hilton Resort Credit (semi-annual)","est_value_usd":200,"reset_cycle":"calendar_year","notify_days_before":[45,14]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_hilton_surpass', 'American Express', 'Hilton Honors Surpass', 'amex', 150, null, false, '{"hilton":12,"dining":6,"groceries":6,"other":3}'::jsonb, '[{"type":"free_night_cert","name":"Free Night Reward (after $15k spend)","est_value_usd":400,"reset_cycle":"cardmember_year","notify_days_before":[60,30]},{"type":"statement_credit","name":"Hilton Credit (quarterly)","est_value_usd":200,"reset_cycle":"calendar_year","notify_days_before":[30,7]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_hilton_nfo', 'American Express', 'Hilton Honors', 'amex', 0, null, false, '{"hilton":7,"dining":5,"groceries":5,"gas":5,"other":3}'::jsonb, '[]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_hyatt', 'Chase', 'World of Hyatt Credit Card', 'visa', 95, null, false, '{"hyatt":4,"dining":2,"gym":2,"transit":2,"other":1}'::jsonb, '[{"type":"free_night_cert","name":"Anniversary Free Night (Cat 1-4)","est_value_usd":200,"reset_cycle":"cardmember_year","notify_days_before":[60,30,7]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_freedom_unlimited', 'Chase', 'Freedom Unlimited', 'visa', 0, null, false, '{"dining":3,"drugstores":3,"travel_portal":5,"other":1.5}'::jsonb, '[]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_freedom_flex', 'Chase', 'Freedom Flex', 'mastercard', 0, null, false, '{"rotating":5,"dining":3,"drugstores":3,"other":1}'::jsonb, '[]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_bcp', 'American Express', 'Blue Cash Preferred', 'amex', 95, null, false, '{"groceries":6,"streaming":6,"transit":3,"gas":3,"other":1}'::jsonb, '[]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_citi_strata_premier', 'Citi', 'Strata Premier', 'mastercard', 95, null, false, '{"travel":3,"dining":3,"groceries":3,"gas":3,"other":1}'::jsonb, '[{"type":"statement_credit","name":"Annual Hotel Credit ($500+ booking)","est_value_usd":100,"reset_cycle":"cardmember_year","notify_days_before":[60,14]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_citi_double_cash', 'Citi', 'Double Cash', 'mastercard', 0, null, false, '{"other":2}'::jsonb, '[]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_delta_reserve', 'American Express', 'Delta SkyMiles Reserve', 'amex', 650, null, false, '{"delta":3,"other":1}'::jsonb, '[{"type":"companion_pass","name":"Annual Companion Certificate","est_value_usd":500,"reset_cycle":"cardmember_year","notify_days_before":[90,30,7]},{"type":"lounge","name":"Delta Sky Club Access","est_value_usd":0,"reset_cycle":"annual","notify_days_before":[]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_united_explorer', 'Chase', 'United Explorer', 'visa', 95, null, false, '{"united":2,"dining":2,"hotels":2,"other":1}'::jsonb, '[{"type":"statement_credit","name":"United TravelBank / Misc Credits","est_value_usd":100,"reset_cycle":"calendar_year","notify_days_before":[45,14]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_southwest_priority', 'Chase', 'Southwest Rapid Rewards Priority', 'visa', 149, null, false, '{"southwest":3,"other":1}'::jsonb, '[{"type":"statement_credit","name":"Annual Travel Credit","est_value_usd":75,"reset_cycle":"cardmember_year","notify_days_before":[60,14]},{"type":"other","name":"Anniversary Points (7,500)","est_value_usd":100,"reset_cycle":"cardmember_year","notify_days_before":[14]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_ihg_premier', 'Chase', 'IHG One Rewards Premier', 'mastercard', 99, null, false, '{"ihg":10,"dining":5,"travel":5,"other":3}'::jsonb, '[{"type":"free_night_cert","name":"Anniversary Free Night (40k)","est_value_usd":250,"reset_cycle":"cardmember_year","notify_days_before":[60,30,7]},{"type":"statement_credit","name":"Global Entry / TSA PreCheck Credit","est_value_usd":120,"reset_cycle":"one_time","notify_days_before":[]}]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;
insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values ('cat_wf_autograph', 'Wells Fargo', 'Autograph', 'visa', 0, null, false, '{"travel":3,"dining":3,"gas":3,"transit":3,"streaming":3,"other":1}'::jsonb, '[]'::jsonb, '2026-06-01', 'active') on conflict (id) do nothing;

-- Program reference
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('hyatt', 'World of Hyatt', 1.5, 1.7, 2.3, 'fixed_chart', '{"1":{"off_peak":3500,"standard":5000,"peak":6500},"2":{"off_peak":6500,"standard":8000,"peak":9500},"3":{"off_peak":9000,"standard":12000,"peak":15000},"4":{"off_peak":12000,"standard":15000,"peak":18000},"5":{"off_peak":17000,"standard":20000,"peak":23000},"6":{"off_peak":21000,"standard":25000,"peak":29000},"7":{"off_peak":25000,"standard":30000,"peak":35000},"8":{"off_peak":35000,"standard":40000,"peak":45000}}'::jsonb, null, 'Points expire after 24 months of inactivity.') on conflict (program) do nothing;
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('bonvoy', 'Marriott Bonvoy', 0.6, 0.8, 1, 'dynamic', null, null, 'Points expire after 24 months of inactivity.') on conflict (program) do nothing;
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('hilton', 'Hilton Honors', 0.4, 0.5, 0.6, 'dynamic', null, null, 'Points expire after 24 months of inactivity.') on conflict (program) do nothing;
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('ihg', 'IHG One Rewards', 0.5, 0.6, 0.7, 'dynamic', null, null, 'Points expire after 12 months of inactivity.') on conflict (program) do nothing;
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('amex_mr', 'Amex Membership Rewards', 1, 1.7, 2, 'dynamic', null, '{"bonvoy":1,"hilton":2,"delta_skymiles":1}'::jsonb, 'No expiration while you hold an eligible card.') on conflict (program) do nothing;
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('chase_ur', 'Chase Ultimate Rewards', 1, 1.7, 2.1, 'dynamic', null, '{"hyatt":1,"bonvoy":1,"united":1,"southwest":1,"ihg":1}'::jsonb, 'No expiration while you hold an eligible card.') on conflict (program) do nothing;
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('capital_one', 'Capital One Miles', 0.8, 1.4, 1.8, 'dynamic', null, '{"bonvoy":1,"alaska":0.75}'::jsonb, 'Miles do not expire while the account is open.') on conflict (program) do nothing;
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('citi_typ', 'Citi ThankYou Points', 1, 1.6, 2, 'dynamic', null, '{"jetblue":1}'::jsonb, 'Points expire 12 months after account closure.') on conflict (program) do nothing;
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('united', 'United MileagePlus', 1, 1.3, 1.6, 'dynamic', null, null, 'Miles do not expire.') on conflict (program) do nothing;
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('delta_skymiles', 'Delta SkyMiles', 1, 1.2, 1.4, 'dynamic', null, null, 'Miles do not expire.') on conflict (program) do nothing;
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('southwest', 'Southwest Rapid Rewards', 1.2, 1.4, 1.5, 'revenue_based', null, null, 'Points do not expire.') on conflict (program) do nothing;
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('jetblue', 'JetBlue TrueBlue', 1.1, 1.3, 1.5, 'revenue_based', null, null, 'Points do not expire.') on conflict (program) do nothing;
insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values ('alaska', 'Alaska Mileage Plan', 1.2, 1.8, 2.4, 'dynamic', null, null, 'Miles expire after 24 months of inactivity.') on conflict (program) do nothing;
