// Generates supabase/seed.sql from the TypeScript source of truth so the live
// DB and the bundled mock data never drift. Run: npx tsx scripts/gen-seed.ts
import { writeFileSync } from 'node:fs';
import { CARD_CATALOG } from '../src/data/catalog';
import { PROGRAM_LIST } from '../src/data/programReference';

const q = (s: string) => "'" + s.replace(/'/g, "''") + "'";
const j = (v: unknown) => q(JSON.stringify(v)) + '::jsonb';
const nullable = (s: string | null) => (s == null ? 'null' : q(s));

const lines: string[] = [
  '-- AUTO-GENERATED by scripts/gen-seed.ts — do not edit by hand.',
  '-- Seed for the two global tables that "are the product".',
  '',
  '-- Card catalog',
];

for (const c of CARD_CATALOG) {
  lines.push(
    `insert into card_catalog (id, issuer, product_name, network, annual_fee, referral_url, referral_active, earn_rates, benefits_template, last_verified_at, status) values (` +
      [
        q(c.id),
        q(c.issuer),
        q(c.product_name),
        q(c.network),
        String(c.annual_fee),
        nullable(c.referral_url),
        String(c.referral_active),
        j(c.earn_rates),
        j(c.benefits_template),
        q(c.last_verified_at),
        q(c.status),
      ].join(', ') +
      ') on conflict (id) do nothing;',
  );
}

lines.push('', '-- Program reference');
for (const p of PROGRAM_LIST) {
  lines.push(
    `insert into program_reference (program, display_name, cpp_low, cpp_mid, cpp_high, pricing_model, chart, transfer_partners, expiration_rule_text) values (` +
      [
        q(p.program),
        q(p.display_name),
        String(p.cpp_low),
        String(p.cpp_mid),
        String(p.cpp_high),
        q(p.pricing_model),
        p.chart ? j(p.chart) : 'null',
        p.transfer_partners ? j(p.transfer_partners) : 'null',
        q(p.expiration_rule_text),
      ].join(', ') +
      ') on conflict (program) do nothing;',
  );
}

import { join } from 'node:path';
const out = join(process.cwd(), 'supabase/seed.sql');
writeFileSync(out, lines.join('\n') + '\n');
console.log(`Wrote ${out} (${CARD_CATALOG.length} cards, ${PROGRAM_LIST.length} programs)`);
